name: ajianaz_dev
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.3
  scrollable_positioned_list: ^0.3.5
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logos/logo_app.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/logos/logo_app.png'
    # background_color: '#hexcode'
    # theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/logos/logo_app.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/logos/logo_app.png'

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    # - assets/images/
    - assets/icons/
